// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Isomorphic helper to get environment variables
function getEnv(key: string): string | undefined {
  // 1. Browser/Vite check
  if (typeof window !== 'undefined') {
    return (import.meta.env as any)[`VITE_${key}`];
  }

  // 2. Server-side check (TanStack Start/Cloudflare)
  // We use a global check to avoid importing server-only modules in the browser bundle
  const globalEnv = (globalThis as any).process?.env || {};
  return globalEnv[`VITE_${key}`] || globalEnv[key];
}

function createSupabaseClient() {
  const url = getEnv('SUPABASE_URL');
  const key = getEnv('SUPABASE_PUBLISHABLE_KEY') || getEnv('SUPABASE_ANON_KEY');

  if (!url || !key) {
    if (typeof window !== 'undefined') {
      console.warn('Supabase configuration missing. Ensure VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY are set.');
    }
    return null as any;
  }

  return createClient<Database>(url, key, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
